# Markdownlint configuration for Slither Random Forest
# See https://github.com/DavidAnson/markdownlint/blob/v0.29.0/schema/.markdownlint.yaml

# Default state for all rules
default: true

# MD003/heading-style - Heading style
MD003:
  # Heading style
  style: "atx"

# MD007/ul-indent - Unordered list indentation
MD007:
  # Spaces for indent
  indent: 2

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 100
  # Number of characters for headings
  heading_line_length: 100
  # Number of characters for code blocks
  code_block_line_length: 120
  # Include code blocks
  code_blocks: true
  # Include tables
  tables: true
  # Include headings
  headings: true
  # Include headings
  headers: true
  # Strict length checking
  stern: false

# MD024/no-duplicate-heading - Multiple headings with the same content
MD024:
  # Only check sibling headings
  siblings_only: true

# MD033/no-inline-html - Inline HTML
MD033:
  # Allowed elements
  allowed_elements: ["br", "sub", "sup", "kbd", "img"]

# MD046/code-block-style - Code block style
MD046:
  # Block style
  style: "fenced"

# MD048/code-fence-style - Code fence style
MD048:
  # Code fence style
  style: "backtick"